application: bicycle-fatalities-vis
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.html
  
- url: /index.html
  script: index.html

- url: /client
  static_dir: client
  
- url: /server
  static_dir: server
  
- url: /php
  static_dir: php